config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("", include("todo.core.urls"))]

todo/core/urls.py
from django.urls import path
from .views import TodoDoneView, TodoListView, TodoItemView, TodoUndoneView, index


app_name = "todo"
urlpatterns = [
    path("", index),
    path("htmx/todo/items/<int:pk>/", TodoItemView.as_view(), name="items"),
    path(
        "htmx/todo/items/<int:pk>/done/",
        TodoDoneView.as_view(),
        name="done",
    ),
    path(
        "htmx/todo/items/<int:pk>/undone/",
        TodoUndoneView.as_view(),
        name="undone",
    ),
    path("htmx/todo/items/", TodoListView.as_view(), name="items-list"),
]

todo/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Todo(BaseModel):
    description = models.CharField(max_length=255)
    is_done = models.BooleanField(default=False)

    class Meta:
        ordering = ["-created_at"]

todo/core/forms.py
from django import forms

from crispy_forms.helper import FormHelper


class AddTodoForm(forms.Form):
    description = forms.CharField(max_length=255)

todo/core/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views import View
from django_htmx.http import trigger_client_event

from .forms import AddTodoForm
from .models import Todo


def index(request):
    items = Todo.objects.all().order_by("-created_at")
    form = AddTodoForm()
    return render(request, "todo/index.html", context={"items": items, "form": form})


class TodoListView(View):
    def post(self, request):
        form = AddTodoForm(request.POST)
        if not form.is_valid():
            return render(request, "todo/add_item_form.html", context={"form": form})

        item = Todo.objects.create(description=form.cleaned_data["description"])
        response = render(
            request, "todo/add_item_form.html", context={"form": form, "item": item}
        )
        # trigger_client_event(response, "todo_item_created", {})
        return response


class TodoItemView(View):
    def delete(self, request, pk):
        todo = get_object_or_404(Todo, pk=pk)
        todo.delete()
        return HttpResponse("ok")


class TodoDoneView(View):
    def post(self, request, pk):
        todo = get_object_or_404(Todo, pk=pk)
        todo.is_done = True
        todo.save()
        return render(request, "todo/item.html", context={"item": todo})


class TodoUndoneView(View):
    def post(self, request, pk):
        todo = get_object_or_404(Todo, pk=pk)
        todo.is_done = False
        todo.save()
        return render(request, "todo/item.html", context={"item": todo})

todo/templates/todo/add_item_form.html
{% if item %}
<div hx-swap-oob="afterbegin:#todo-items">
    {% include "todo/item.html" with item=item %}
</div>
{% endif %}
<form hx-post="{% url 'todo:items-list' %}" hx-target="this" hx-swap="outerHTML" class="flex justify-between my-4">
    <div class="form-control flex-1 mr-2">
        {% if form.description.errors %}
        <input type="text" class="input input-bordered input-error" placeholder="What to do?"
            name="{{form.description.name}}" autocomplete="off" />
        <label class="label">
            {% for error in form.description.errors %}
            <span class="label-text-alt text-error">{{error|escape}}</span>
            {% endfor %}
        </label>
        {% else %}
        <input type="text" class="input input-bordered" placeholder="What to do?" name="{{form.description.name}}"
            autocomplete="off" />
        {% endif %}
    </div>
    <div class="form-control">
        <button class="btn bg-success">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-1" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
            </svg>
            Add Item
        </button>
    </div>
</form>

todo/templates/todo/base.html
{% load static %}
{% load django_htmx %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% tailwind_css %}
  {% block head %}{% endblock %}
</head>

<body hx-headers='{"X-CSRFToken": "{{csrf_token}}"}'>
  {% block content %}{% endblock %}
</body>

<script src="{% static 'htmx.min.js' %}"></script>
{% django_htmx_script %}

</html>

todo/templates/todo/index.html
{% extends "todo/base.html" %}
{% load crispy_forms_tags %}

{% block head %}
<style>
    .fade-out.htmx-swapping {
        opacity: 0;
        transition: opacity 0.5s ease-out;
    }

    .fade-in.htmx-added {
        opacity: 0;
    }

    .fade-in {
        opacity: 1;
        transition: opacity 0.5s ease-out;
    }
</style>
{% endblock %}

{% block content %}
<div class="flex flex-col p-16 items-center justify-items-center">
    <h1 class="font-medium text-3xl my-2">Todo App</h1>
    <div class="flex flex-col w-full max-w-xl">
        {% include "todo/add_item_form.html" %}
        <div id="todo-items">
            {% for i in items %}
            {% include "todo/item.html" with item=i %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

todo/templates/todo/item.html
<div hx-target="this"
    class="flex border rounded-md p-4 border-slate-200 justify-between shadow-md mb-4 fade-out fade-in">
    <div class="flex flex-row items-center">
        <div class="mx-2">
            {% if item.is_done %}
            <input type="checkbox" hx-post="{% url 'todo:undone' item.pk %}" hx-swap="outerHTML"
                class="checkbox checkbox-lg checkbox-accent" checked>
            {% else %}
            <input type="checkbox" hx-post="{% url 'todo:done' item.pk %}" hx-swap="outerHTML"
                class="checkbox checkbox-lg checkbox-accent">
            {% endif %}
        </div>
        <span
            class="inline-block text-lg align-middle {% if item.is_done %}line-through text-slate-400{% else %}text-slate-700{% endif %}">{{item.description}}</span>
    </div>
    <button class="btn btn-circle btn-outline btn-error" hx-delete="{% url 'todo:items' item.pk %}"
        hx-swap="delete swap:0.5s" hx-confirm="Are you sure you want to delete?">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
    </button>
</div>

todo/templates/todo/todo_items.html
<div id="todo-items">
    {% for i in items %}
    {% include "todo/item.html" with item=i %}
    {% endfor %}
</div>